# Generated by Django 4.1.4 on 2022-12-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('RESERVADO', 'RESERVADO'), ('COMPLETADA', 'COMPLETADA'), ('ANULADA', 'ANULADA'), ('NO ASISTEN', 'NO ASISTEN')], max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serialApp.institucion')),
            ],
        ),
    ]
