# Generated by Django 4.1.1 on 2022-10-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horareserva',
            field=models.TimeField(),
        ),
    ]
