# Generated by Django 4.1.1 on 2022-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_horareserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
