# Generated by Django 4.1.1 on 2022-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
