# Generated by Django 4.1.4 on 2022-12-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_inscripcion_delete_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inscripcion',
        ),
    ]
